name: Build Mod

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    
    - name: 设置JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: 设置执行权限
      run: chmod +x ./gradlew
    
    - name: Gradle构建
      run: ./gradlew build
    
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: mod-jar
        path: build/libs/*.jar
        retention-days: 7